### ISSUE TITLE
Correct depth data for VWC and create new merged file 

### ISSUE THREAD

**Issue by AnastasiaAVM** [davidjpmoore/Fsoil_aridlands#7]

**Comment by AnastasiaAVM** [comment]
VWC - volumetric water content
TS - soil temperature

**_P*_1_H*     Variable(VWC/TS)_Plot Number(1-12)_Sensor depth(0-12cm)_House number (1-5)
**_P*_2_H*     Variable(VWC/TS)_Plot Number(1-12)_Sensor depth(25cm)_House number(1-5)
**_P*_3_H*     Variable(VWC/TS)_Plot Number(1-12)_Sensor depth(75cm)_House number(1-5)

**Comment by davidjpmoore** [comment]
@AnastasiaAVM 

This is the VWC data filtered by probe 1 (5mm) - it does not seem right?

![RM_VWC_by_Treatment_5mm](https://user-images.githubusercontent.com/6138344/168405297-3e221dfd-a495-4c30-8562-0e4fdda2949f.png)

**Comment by davidjpmoore** [comment]
flux_RM_VWC_precip_BYTRT
# A tibble: 4 × 4
  Summer Mean_Fsoil_TRT Mean_VWC_TRT Mean_Precip_TRT
  <chr>           <dbl>        <dbl>           <dbl>
1 S1               19.4         2.23            10.4
2 S2               18.0         2.48            10.4
3 S3               19.7         2.53            10.0
4 S4               17.8         2.33            10.3

**Comment by AnastasiaAVM** [comment]
The first column in the table - is it a flux rate?

**Comment by AnastasiaAVM** [comment]
@davidjpmoore About the graph - the differences now are not really visible - Maybe we can look for the daily mean? or another type of graph?

**Comment by davidjpmoore** [comment]
> The first column in the table - is it a flux rate?
The columns are as follows
1. Summer 
2. Mean_Fsoil_TRT 
3. Mean_VWC_TRT 
4. Mean_Precip_TRT

**Comment by AnastasiaAVM** [comment]
They have very high flux rates.
